/*
    version.h — generated by CMake in the upstream build; this is the static
    stand-in so the core can be compiled without CMake.
*/
#ifndef VERSION_H
#define VERSION_H

#define MELONDS_URL            "https://melonds.kuribo64.net"

#define MELONDS_VERSION_BASE   "1.1"
#define MELONDS_VERSION_SUFFIX " (Pokemon Access iOS)"
#define MELONDS_VERSION        MELONDS_VERSION_BASE MELONDS_VERSION_SUFFIX

#endif // VERSION_H
