#!/usr/bin/env python3
"""gen-fe-plan.py — write an input plan that PLAYS Fire Emblem, not just mashes A.

⛔ WHY. A pure-A-mash plan cannot get past FE11's Prologue: the movement tutorial
puts up a popup reading "Marth can move anywhere within the blue area" and waits for
the unit to actually MOVE. Pressing A forever leaves the game parked on that tutorial
— which is exactly what happened, and it is why a 15,500-frame run reported the
faction census unchanged (player=1 enemy=0) and looked like "this map has no enemies"
when the real cause was "the tutorial was never satisfied".

The Prologue maps genuinely have no enemies (confirmed by screenshot AND by the
faction census), so reaching a hostile force means completing the Prologue: select
Marth, move him, confirm, choose Wait, then end the turn — repeatedly.

Emits:  KEY <frame> <BTN> <1|0>
"""
import sys

BTN_WAIT = 30          # frames to hold a button
GAP = 60               # frames between actions

def plan(path, iterations=18, move_steps=3):
    out = []
    f = 200

    def press(btn, hold=BTN_WAIT):
        """Emit a press+release pair and advance the clock."""
        nonlocal f
        out.append(f"KEY {f} {btn} 1")
        out.append(f"KEY {f + hold} {btn} 0")
        f += GAP

    # ---- boot to the first map (same preamble the working plans use) ----
    for _ in range(20):
        press("A")
    press("START", 40)
    for _ in range(10):
        press("A")
    press("START", 40)
    for _ in range(8):
        press("A")

    # ---- now actually play: move Marth, confirm, wait, end turn ----
    for i in range(iterations):
        # Select the unit under the cursor.
        press("A")
        # Walk it. Direction alternates so it does not stall against a wall.
        d = "RIGHT" if (i % 2 == 0) else "LEFT"
        for _ in range(move_steps):
            press(d, 20)
        # Confirm the destination -> the action menu appears.
        press("A")
        # Choose "Wait" (first entry) then dismiss any tutorial popup that follows.
        press("A")
        press("A")
        press("B")            # close a tutorial box if one is up ("press B to cancel")
        # End the turn so the enemy phase (if any) runs.
        press("START", 40)
        press("A")
        press("A")

    with open(path, "w") as fh:
        fh.write("# GENERATED by scripts/gen-fe-plan.py — do not hand-edit.\n")
        fh.write("# Plays the Prologue: select, move, confirm, Wait, end turn.\n\n")
        fh.write("\n".join(out))
        fh.write("\n")
    print(f"wrote {path}: {len(out)} events, last frame {f}")


if __name__ == "__main__":
    path = sys.argv[1] if len(sys.argv) > 1 else "fe/plans/play.txt"
    iters = int(sys.argv[2]) if len(sys.argv) > 2 else 18
    plan(path, iters)
