#!/usr/bin/env bash
# package-sim-app.sh — assemble a real iOS-Simulator .app bundle.
#
# Two ways in:
#   1. A binary already linked by `xtool dev build --triple …-simulator` (Linux/WSL
#      path; xtool links but only packages the DEVICE triple, so the bundle is
#      assembled here from the linked binary + resources).
#   2. No pre-linked binary (e.g. a macOS CI runner, which has Xcode but not
#      xtool): link it here with swift build against the simulator triple.
#
# ⛔ The second path exists because CI failed with "no simulator binary at
# .build/... — run build-sim-app.sh first". The core had built fine; only the
# Swift link step was missing, because that step was assumed to have happened
# elsewhere. This script now does it when it has not.
set -uo pipefail
ROOT="${ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
# Portable Mach-O platform detection (llvm-objdump / vtool / otool). Shared with
# verify-sim-app.sh because both must answer "simulator or device?" and the first
# inline version only knew about llvm-objdump, which macOS runners do not have.
. "$ROOT/scripts/lib-macho.sh"
APP="$ROOT/xtool-sim/PokemonAccess.app"
BIN="$ROOT/.build/arm64-apple-ios-simulator/debug/PokemonAccess-App"
BUNDLE_ID="com.devinprater.pokemonaccess"
TRIPLE="${TRIPLE:-arm64-apple-ios-simulator}"

if [ ! -f "$BIN" ]; then
  echo "== no pre-linked simulator binary; building it here with swift build"
  SIMLIB="$ROOT/Vendor/sim/libpokecore-sim.a"
  [ -f "$SIMLIB" ] || { echo "!! simulator core archive missing: $SIMLIB" >&2; exit 1; }
  cd "$ROOT" || exit 1
  export POKECORE_LIB="$SIMLIB"

  # ⛔ xtool FIRST. The package is a LIBRARY, not an executable — the app wrapper
  # (entry point, Info.plist, bundle layout) is generated by xtool. A bare
  # `swift build` compiles the library and produces nothing to package. xtool is
  # therefore attempted first when it is available, and the raw SwiftPM path below
  # is a fallback for an environment with no xtool.
  if command -v xtool >/dev/null 2>&1; then
    echo "   xtool found; using it (this is how the working local build is made)"
    # ⛔ --triple is REQUIRED here. A bare `xtool dev build` targets the DEVICE
    # triple and links Vendor/libpokecore.a, which is not what this script's caller
    # built — it fails with "link command failed with exit code 1" and yields no
    # simulator binary. The simulator triple links against the archive built by
    # build-sim.sh.
    xtool dev build --triple "$TRIPLE" 2>&1 | tail -25 || true
  fi
fi

# xtool places a simulator-linked binary under a simulator triple directory; check
# for it before falling back to swift build.
if [ ! -f "$BIN" ]; then
  for cand in \
    "$ROOT/.build/$TRIPLE/debug/PokemonAccess-App" \
    "$ROOT/.build/arm64-apple-ios-simulator/debug/PokemonAccess-App" \
    "$ROOT/.build/arm64-apple-ios17.0-simulator/debug/PokemonAccess-App"
  do
    [ -f "$cand" ] && BIN="$cand" && break
  done
fi

if [ ! -f "$BIN" ]; then
  echo "== still no simulator binary; attempting a direct swift build"
  SIMLIB="$ROOT/Vendor/sim/libpokecore-sim.a"
  [ -f "$SIMLIB" ] || { echo "!! simulator core archive missing: $SIMLIB" >&2; exit 1; }
  cd "$ROOT" || exit 1
  export POKECORE_LIB="$SIMLIB"

  # ⛔ swift build MUST be told which SDK to use, but NOT via --sdk: that flag also
  # applies to compiling the package MANIFEST, which must be built for the host.
  # It fails with "Invalid manifest ... unable to load standard library for target
  # 'arm64-apple-macosx14.0'", which reads like a broken Package.swift.
  # A destination file is SwiftPM's supported way to cross-compile: the manifest is
  # built for the host, the product for the target.
  SIMSDK="${SDKROOT:-}"
  if [ -z "$SIMSDK" ] && command -v xcrun >/dev/null 2>&1; then
    SIMSDK="$(xcrun --sdk iphonesimulator --show-sdk-path 2>/dev/null || true)"
  fi
  if [ -z "$SIMSDK" ] && [ -d "$HOME/.swiftpm/swift-sdks/darwin.artifactbundle" ]; then
    SIMSDK="$(find "$HOME/.swiftpm/swift-sdks/darwin.artifactbundle/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs" -maxdepth 1 -name 'iPhoneSimulator*.sdk' 2>/dev/null | head -1)"
  fi
  [ -d "${SIMSDK:-}" ] || { echo "!! no iPhoneSimulator SDK found (set SDKROOT)" >&2; exit 1; }
  echo "   SDK: $SIMSDK"

  TC_BIN="$(dirname "$(command -v swift 2>/dev/null || echo /usr/bin/swift)")"
  DEST_JSON="$ROOT/.build/sim-destination.json"
  mkdir -p "$ROOT/.build"
  python3 - "$SIMSDK" "$TRIPLE" "$TC_BIN" > "$DEST_JSON" <<'PYJSON'
import json, sys
sdk, target, tcbindir = sys.argv[1], sys.argv[2], sys.argv[3]
json.dump({
    "version": 1,
    "sdk": sdk,
    "target": target,
    "toolchain-bin-dir": tcbindir,
    "extra-cc-flags": [],
    "extra-swiftc-flags": [],
    "extra-cpp-flags": [],
}, sys.stdout, indent=2)
PYJSON
  swift build --destination "$DEST_JSON" -c debug 2>&1 | tail -25 || true
fi

# ⛔ NEVER take the first file named PokemonAccess-App. A `.dSYM/.../DWARF/`
# companion file has the same name and IS a valid Mach-O, so a naive `find | head -1`
# happily packages debug symbols as the app — and since the device build is usually
# present too, the result was a 41 MB bundle reported as "platform ios", i.e. a
# device binary wearing a simulator Info.plist. Validate the platform before accepting.
# macho_platform comes from scripts/lib-macho.sh and returns a normalised word.
pick_sim_binary() {
  local cand plat
  for cand in \
    "$ROOT/.build/$TRIPLE/debug/PokemonAccess-App" \
    "$ROOT/.build/arm64-apple-ios-simulator/debug/PokemonAccess-App" \
    "$ROOT/.build/arm64-apple-ios17.0-simulator/debug/PokemonAccess-App"
  do
    [ -f "$cand" ] || continue
    case "$cand" in *.dSYM/*) continue ;; esac
    plat="$(macho_platform "$cand")"
    if [ "$plat" = "iossimulator" ]; then echo "$cand"; return 0; fi
  done
  # xtool may only leave the binary inside its own bundle; fall back to that.
  for cand in "$ROOT/xtool-sim/PokemonAccess.app/PokemonAccess" \
              "$ROOT/xtool/PokemonAccess.app/PokemonAccess"; do
    [ -f "$cand" ] || continue
    plat="$(macho_platform "$cand")"
    if [ "$plat" = "iossimulator" ]; then echo "$cand"; return 0; fi
  done
  return 1
}

if [ ! -f "$BIN" ]; then
  FOUND="$(pick_sim_binary || true)"
  if [ -n "$FOUND" ]; then
    BIN="$FOUND"
    echo "   using $BIN"
  else
    echo "!! no simulator-platform binary found (detection tools present:$(macho_platform_tools))" >&2
    echo "   candidates the build produced:" >&2
    find "$ROOT/.build" "$ROOT/xtool" "$ROOT/xtool-sim" -name 'PokemonAccess*' -type f 2>/dev/null \
      | head -8 | while read -r f; do
          echo "     $f  [$(macho_platform "$f")]" >&2
        done
    exit 1
  fi
fi

# Final guard: refuse to package anything that is not simulator-platform. Silent
# acceptance here is exactly how the wrong binary got shipped before.
PLATF="$(macho_platform "$BIN")"
if [ "$PLATF" != "iossimulator" ]; then
  echo "!! refusing to package: $BIN is '$PLATF', not iossimulator" >&2
  echo "   detected via:$(macho_platform_tools)" >&2
  macho_platform_raw "$BIN" | sed 's/^/   /' >&2
  exit 1
fi

[ -f "$BIN" ] || { echo "!! could not produce a simulator binary (looked at $BIN)" >&2; exit 1; }

echo
echo "== binary =="
file "$BIN"
PLAT="$(macho_platform "$BIN")"
echo "LC_BUILD_VERSION: platform ${PLAT} ($(macho_platform_raw "$BIN" 2>/dev/null | tr -s ' ' | sed 's/^ *//' || echo '<not found>'))"
case "$PLAT" in
  iossimulator) echo "-> iOS Simulator platform (correct)" ;;
  ios)          echo "!! device platform — the linker picked the DEVICE target" ;;
  *)            echo "!! could not confirm the platform (detection tools:$(macho_platform_tools))" ;;
esac

rm -rf "$APP"
mkdir -p "$APP"
cp "$BIN" "$APP/PokemonAccess"

# The SwiftPM resource bundle travels with the app: it holds the Lua script, so an
# app assembled without it installs and then finds no script.
RES=""
for cand in "$ROOT/.build/arm64-apple-ios-simulator/debug/PokemonAccess_PokemonAccess.bundle" \
            "$ROOT/.build"/*/debug/PokemonAccess_PokemonAccess.bundle; do
  [ -d "$cand" ] && { RES="$cand"; break; }
done
if [ -n "$RES" ]; then
  cp -R "$RES" "$APP/"
  echo "== resources: $(find "$APP/PokemonAccess_PokemonAccess.bundle" -type f | wc -l) files"
  ls "$APP/PokemonAccess_PokemonAccess.bundle/Resources/" 2>/dev/null
else
  echo "!! no resource bundle — the Lua script would be missing from the app" >&2
  exit 1
fi

cat > "$APP/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key><string>en</string>
	<key>CFBundleDisplayName</key><string>Open Game Access</string>
	<key>CFBundleExecutable</key><string>PokemonAccess</string>
	<key>CFBundleIdentifier</key><string>$BUNDLE_ID</string>
	<key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
	<key>CFBundleName</key><string>PokemonAccess</string>
	<key>CFBundlePackageType</key><string>APPL</string>
	<key>CFBundleShortVersionString</key><string>0.1.0</string>
	<key>CFBundleVersion</key><string>1</string>
	<!-- The SIMULATOR platform, not iPhoneOS: this is the pair of keys a
	     simulator runtime validates before it will launch the app. -->
	<key>CFBundleSupportedPlatforms</key><array><string>iPhoneSimulator</string></array>
	<key>DTPlatformName</key><string>iphonesimulator</string>
	<key>MinimumOSVersion</key><string>17.0</string>
	<key>UIDeviceFamily</key><array><integer>1</integer><integer>2</integer></array>
	<key>UILaunchScreen</key><dict/>
	<key>UIRequiredDeviceCapabilities</key><array><string>arm64</string></array>
	<key>UISupportedInterfaceOrientations</key><array><string>UIInterfaceOrientationPortrait</string></array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
</dict>
</plist>
PLIST

# Optional ad-hoc signature; a simulator does not enforce it, but signing makes the
# bundle acceptable to stricter installers.
/usr/local/swift/bin/ldid -S "$APP/PokemonAccess" 2>/dev/null || \
  command -v ldid >/dev/null 2>&1 && ldid -S "$APP/PokemonAccess" 2>/dev/null || \
  echo "(unsigned — fine for a simulator)"

echo
echo "== $APP"
ls -la "$APP"

# ⛔ Plain llvm-nm, no -g/-gU. GNU nm cannot read Mach-O at all, and llvm-nm -g
# on this binary prints a single line — both reported "0 melonDS symbols / 0 poke_"
# for a perfectly linked app, which sent me hunting a link bug that did not exist.
# scripts/verify-sim-app.sh cross-checks this against the total symbol count, so a
# tooling failure can no longer masquerade as a broken build.
NM_BIN=""
for c in /usr/local/swift/bin/llvm-nm llvm-nm /usr/bin/llvm-nm; do
  { [ -x "$c" ] || command -v "$c" >/dev/null 2>&1; } && { NM_BIN="$c"; break; }
done
[ -z "$NM_BIN" ] && NM_BIN="$(command -v nm || echo nm)"

echo "--- total symbols ---"
"$NM_BIN" "$APP/PokemonAccess" 2>/dev/null | wc -l
echo "--- core linked in? (melonDS symbols) ---"
"$NM_BIN" "$APP/PokemonAccess" 2>/dev/null | grep -ci melonds || true
echo "--- poke_ entry points ---"
"$NM_BIN" "$APP/PokemonAccess" 2>/dev/null | grep -c 'poke_' || true
echo "--- script hashes (must equal the originals) ---"
shasum -a 256 "$APP/PokemonAccess_PokemonAccess.bundle/Resources/"*.lua 2>/dev/null || \
  sha256sum "$APP/PokemonAccess_PokemonAccess.bundle/Resources/"*.lua 2>/dev/null

echo "--- zip for a simulator service ---"
cd "$ROOT/xtool-sim"
rm -f PokemonAccess-simulator.zip
zip -qr PokemonAccess-simulator.zip PokemonAccess.app
ls -la PokemonAccess-simulator.zip
