#!/usr/bin/env python3
"""Replace the fake Swift gate with real, provable ones.

⛔ THE PROBLEM: scripts/swift-check.sh says "type-check the Swift targets (no device, no SDK
link)" and then runs four greps. `set -uo pipefail` with no `-e` and no failure path means
it can never fail, and nothing in .github/ or scripts/ calls it. It is not a gate.

WHAT REPLACES IT, and why each is honest:
  * `typecheck` — a REAL swiftc type-check of the files Swift-on-Linux can actually compile.
    Reach is bounded by the SDK: AdapterCommand.swift (Foundation only) and GameSystem.swift
    (needs module CPokeCore, so a module map is provided). The files importing UIKit,
    SwiftUI, AVFoundation or GameController cannot be checked on Linux, and the script SAYS
    SO rather than pretending a grep is a type-check.
  * `mirror` — a real invariant: Core/adapter.h's Command enum and AdapterCommand.swift's
    mirror must agree case-for-case and in order, because the raw values ARE the C ABI. This
    is the bug class that silently rejects a new command with no speech and no error.
  * `poke-symbols` — every poke_ symbol Swift calls must exist in the C header. That is what
    the original greps were reaching for; this version compares the two sets instead of
    printing them.
Exit non-zero on any failure, so it can be wired into CI.
"""
import pathlib
import re
import subprocess
import sys

# ⛔ DERIVED, NEVER HARD-CODED: the CI checkout is not at any dev path.
ROOT = pathlib.Path(__file__).resolve().parent.parent
SWIFT_DIR = ROOT / "Sources" / "OpenGameAccess"
HEADER = ROOT / "Sources" / "CPokeCore" / "include" / "pokecore.h"

# Files importing only Foundation, plus those needing a provided module map.
# Flags per file. Anything importing CPokeCore needs the module map, because that module
# is generated by Xcode on macOS and does not exist off it.
_CORE_MM = ["-I", str(ROOT / "Sources" / "CPokeCore" / "include"),
            "-Xcc", "-fmodule-map-file=" + str(ROOT / "Sources" / "CPokeCore" / "module.modulemap")]

CHECKABLE = {
    "AdapterCommand.swift": [],          # Foundation only
    "CueSynth.swift": _CORE_MM,          # imports CPokeCore for poke_cue_snapshot
    "GameSystem.swift": _CORE_MM,
}
# Files that CANNOT be checked on Linux, with the honest reason.
UNCHECKABLE = {
    "ControllerInput.swift": "imports GameController (Apple-only)",
    "GameSession.swift": "imports SwiftUI/AVFoundation/CPokeCore",
    "InputBridge.swift": "imports SwiftUI/UniformTypeIdentifiers",
    "OpenGameAccessApp.swift": "imports SwiftUI",
    "RootView.swift": "imports SwiftUI/UIKit",
    "SettingsView.swift": "imports SwiftUI",
    "CuePlayer.swift": "imports AVFoundation (Apple-only)",
    "SpeechEngine.swift": "imports UIKit/AVFoundation",
}


def run(cmd):
    p = subprocess.run(cmd, capture_output=True, text=True)
    return p.returncode, (p.stdout + p.stderr)


def slot_consistency():
    """ControllerInput.swift cannot be compiled on Linux (GameController), so its Slot enum is
    checked by parsing. The bug this exists for: chord(for:) returned `.repeatOlder`, which was
    never declared as a Slot case -- a compile error on macOS, invisible here because the file
    is skipped. Invariant: every slot named by chord()/resolve() is a declared case, and every
    declared case has a resolve() arm (otherwise a chord hits the silent "no command" path)."""
    print("-- Slot consistency in ControllerInput.swift (no compiler: Apple-only imports)")
    path = SWIFT_DIR / "ControllerInput.swift"
    if not path.exists():
        print("   ?? ControllerInput.swift missing")
        return False
    src = path.read_text()

    m = re.search(r"private enum Slot \{(.*?)\n    \}", src, re.S)
    if not m:
        print("   ?? could not find the Slot enum")
        return False
    declared = set()
    for line in m.group(1).splitlines():
        line = line.split("///")[0].strip()
        if not line or line.startswith("//"):
            continue
        for name in re.findall(r"\b([a-zA-Z][A-Za-z0-9_]*)\b", line):
            if name != "case":
                declared.add(name)

    cm = re.search(r"private func chord\(for input: Input\) -> Slot\? \{(.*?)\n    \}", src, re.S)
    used = set(re.findall(r"return \.([A-Za-z0-9_]+)", cm.group(1))) if cm else set()

    rm = re.search(r"private func resolve\(_ slot: Slot\) -> Action\? \{(.*?)\n    \}", src, re.S)
    resolved = set(re.findall(r"case \.([A-Za-z0-9_]+):", rm.group(1))) if rm else set()

    ok = True
    missing = used - declared
    if missing:
        print("   x chord() returns slot(s) not declared in Slot: %s" % ", ".join(sorted(missing)))
        ok = False
    unresolved = declared - resolved
    if unresolved:
        print("   x Slot case(s) with no resolve() arm: %s" % ", ".join(sorted(unresolved)))
        ok = False
    if ok:
        print("   ok: %d slot(s) declared, all used declared, all resolved" % len(declared))
    return ok


def unlisted_swift_files():
    """⛔ THE HOLE THIS CLOSES. typecheck() walks CHECKABLE and UNCHECKABLE explicitly, so a
    new .swift file in NEITHER table is silently unguarded -- it is never type-checked and
    never reported as skipped. CuePlayer.swift landed exactly there. A gate that quietly
    ignores an unlisted file is the same failure as the reader-asset check that matched 197
    entries with `grep -qi lua`: it reports success for work it never examined."""
    print("-- every .swift file is accounted for (checked or explicitly skipped)")
    listed = set(CHECKABLE) | set(UNCHECKABLE)
    on_disk = sorted(p.name for p in SWIFT_DIR.glob("*.swift"))
    ghosts = [f for f in on_disk if f not in listed]
    if ghosts:
        for g in ghosts:
            print("   !! %s is in neither CHECKABLE nor UNCHECKABLE" % g)
        print("   Add it to whichever table fits: it is either checkable here or must")
        print("   say WHY it is not. Silence is not a reason.")
        return False
    print("   ok: %d file(s), all accounted for" % len(on_disk))
    return True


def typecheck():
    print("-- real swiftc type-check (Linux-reachable files only)")
    ok = True
    for name, extra in CHECKABLE.items():
        path = SWIFT_DIR / name
        if not path.exists():
            print("   ?? %s missing" % name)
            ok = False
            continue
        # ⛔ SWIFT 6, because that is what the app builds with. Checking at version 5 made
        # this a different program: CueSynth.swift passed at 5 and failed the real build at 6
        # on a concurrency error the gate could not see.
        rc, out = run(["swiftc", "-typecheck", "-swift-version", "6", str(path)] + extra)
        if rc == 0:
            print("   ok: %s" % name)
        else:
            print("   !! %s failed to type-check:" % name)
            for line in out.splitlines()[:12]:
                print("      %s" % line)
            ok = False
    for name, why in UNCHECKABLE.items():
        print("   -- skipped: %-26s %s" % (name, why))
    print("   ⛔ A skipped file is NOT a verified file. Only the SDK blocks it, not the tool.")
    return ok


def poke_symbols():
    print("-- every poke_ symbol Swift calls exists in the C header")
    if not HEADER.exists():
        print("   !! header missing")
        return False
    declared = set(re.findall(r'\b(poke_[a-z_]+)\s*\(', HEADER.read_text(encoding="utf-8")))
    called = set()
    for f in SWIFT_DIR.glob("*.swift"):
        called |= set(re.findall(r'\b(poke_[a-z_]+)\b', f.read_text(encoding="utf-8")))
    missing = sorted(called - declared)
    if missing:
        for m in missing:
            print("   !! called but not declared: %s" % m)
        return False
    print("   ok: %d symbols called, all declared" % len(called))
    return True


def main():
    which = sys.argv[1] if len(sys.argv) > 1 else "all"
    ok = True

    if which in ("all", "typecheck"):
        ok = typecheck() and ok
    ok = slot_consistency() and ok
    ok = unlisted_swift_files() and ok
    if which in ("all", "poke-symbols"):
        ok = poke_symbols() and ok

    print()
    if ok:
        print("PASS: swift-check (real checks only; skipped files are named above)")
        return 0
    print("FAIL: swift-check")
    return 1


if __name__ == "__main__":
    sys.exit(main())
