#!/usr/bin/env bash
# vendor-pokemon-ds.sh — bundle Ola's multi-file DS tree into the single-file
# main.lua both apps ship.
#
# WHY: the apps concatenate (bizhawk_compat.lua + main.lua) into ONE Lua chunk
# (see GameSession.bundledScript / LuaScriptRunner.loadScript). Ola's tree
# (third-party/pokemon-ds/) is a loader + core/ + games/ that finds its parts
# with relative loadfile()/io.open() — which resolve against BizHawk's
# per-resume working directory and do not exist on a phone. So the tree
# travels INSIDE this file: a PRELOAD table plus loadfile/io.open overrides
# that consult it first and fall back to the real ones.
#
# ⛔ ZERO STANDING LOCALS: the loader chunk shares the 200-locals budget the
# shim's header documents (declaring even four top-level locals once broke the
# whole chunk). Everything here lives in ONE `do ... end` block; the overrides
# are globals/table fields closing over a block-local table.
#
# Update flow: re-copy Ola's tree into third-party/pokemon-ds/, run this,
# commit the tree + both outputs. Outputs are generated — never edit them.
set -uo pipefail
case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*)
    # Native Windows python cannot read MSYS /c/... paths: use the C:/... form.
    ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -W)"
    ;;
  *)
    ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
    ;;
esac
cd "$ROOT" || exit 1

python3 - "$ROOT" <<'PYEOF'
import hashlib, os, sys

root = sys.argv[1]
src = os.path.join(root, "third-party", "pokemon-ds")
outs = [
    os.path.join(root, "app", "src", "main", "assets", "lua", "main.lua"),
    os.path.join(root, "Sources", "OpenGameAccess", "Resources", "main.lua"),
]

def read(p):
    with open(p, "rb") as f:
        data = f.read().decode("utf-8")
    # Ola's tree is CRLF; the repo is LF. Strip only the \r in \r\n pairs.
    return data.replace("\r\n", "\n")

def bracket_level(text):
    # Lowest long-bracket level whose closer does not occur in the text.
    level = 0
    while "]" + "=" * level + "]" in text:
        level += 1
        if level > 16:
            raise SystemExit("file needs a bracket level above 16 — refusing")
    return level

loader = read(os.path.join(src, "main.lua"))

# Every loadable part, keyed EXACTLY as the loader spells the path:
# games/<set>.lua via the GAMES table, core/<name>.lua via core().
embedded = {}
for dirpath, _, filenames in os.walk(src):
    for fn in sorted(filenames):
        if not fn.endswith(".lua"):
            continue
        full = os.path.join(dirpath, fn)
        rel = os.path.relpath(full, src).replace(os.sep, "/")
        if rel == "main.lua":
            continue
        embedded[rel] = read(full)
if not embedded:
    raise SystemExit("no loadable .lua parts found under " + src)

parts = []
manifest = []
for rel in sorted(embedded):
    text = embedded[rel]
    lv = bracket_level(text)
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()[:12]
    manifest.append("  -- %-18s %7d bytes  sha256:%s" % (rel, len(text), digest))
    parts.append('  [%s] = [%s[\n%s]%s],' % (
        '"%s"' % rel, "=" * lv, text, "=" * lv))

header = """-- GENERATED by scripts/vendor-pokemon-ds.sh from third-party/pokemon-ds/.
-- Do not edit this file: re-copy Ola's tree, re-run the script, commit both.
-- The loader body below is byte-identical (modulo CRLF) to the tree's main.lua;
-- the multi-file parts it loadfiles live in PRELOAD so the single mobile chunk
-- keeps working. Embedded files:
%s
do

local PRELOAD = {
%s
}

-- loadfile: answer from the bundle first, fall back to the real one.
local __real_loadfile = loadfile
function loadfile(path)
    local src = PRELOAD[path]
    if src ~= nil then
        local chunk, err = load(src, "@" .. path)
        return chunk, err
    end
    if __real_loadfile then return __real_loadfile(path) end
    return nil, "not bundled and no filesystem loader: " .. tostring(path)
end

-- io.open: answer READS from the bundle (the loader's existence check);
-- writes fall through to the real io (dev dump files stay dev-only).
local __real_io_open = io.open
function io.open(path, mode)
    if (mode == "r" or mode == nil) and PRELOAD[path] ~= nil then
        return { close = function() end }
    end
    if __real_io_open then return __real_io_open(path, mode) end
    return nil, "not bundled: " .. tostring(path), 2
end

end -- do block: no top-level locals may escape (see the shim header note)
""" % ("\n".join(manifest), "\n".join(parts))

bundle = header + "\n" + loader

# Round-trip: slice every embedded entry back out of the bundle by its exact
# literal span and require it to equal the source. A corrupt bundle that still
# parses is the failure this guards against.
for rel in sorted(embedded):
    text = embedded[rel]
    lv = bracket_level(text)
    openlit = '["%s"] = [%s[\n' % (rel, "=" * lv)
    closelit = "]%s]," % ("=" * lv)
    i = bundle.find(openlit)
    assert i >= 0, rel
    j = bundle.find(closelit, i + len(openlit))
    assert j >= 0, rel
    got = bundle[i + len(openlit):j]
    # The entry is followed by "\n" before the closer in our layout ("...text\n]===],").
    assert got == text + "\n" or got == text, "round-trip mismatch: " + rel

for out in outs:
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(bundle)
    print("wrote %s (%d bytes, %d embedded files)" % (out, len(bundle), len(embedded)))
PYEOF
